baseUrl : 'https://itsabhinavm.github.io/'
languagecode : en-us
title :   Abhinav M
theme : PaperMod

params :
  homeInfoParams :
    Title : "Howdy ! 👋"
    Content : "Welcome to my first hugo project !"

  cover :
    linkFullImages : true
  ShowBreadCrumbs : true
  showReadingTime : true
  ShowShareButtons : true
  ShowPostNavlinks : true
menu:
  main:
    - name: "Home"
      weight: 1
      identifier: "home"
      url: "/"

    - name: "About"
      weight: 2
      identifier: "about"
      url: "/about/"

    - name: "Blog"
      weight: 3
      identifier: "blog"
      url : "/blog/"
      



